version: "3.8"
services:
  postgres:
    image: library/postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./postgres/:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"

  backend-todo-list:
    image: romanowalex/backend-todo-list:v1.0
    container_name: backend-todo-list
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  frontend-todo-list:
    build: .
    image: romanowalex/frontend-todo-list:v1.0
    container_name: frontend-todo-list
    restart: on-failure
    ports:
      - "3000:80"
    depends_on:
      - backend-todo-list

volumes:
  db-data:
