apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-todo
  namespace: practice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-todo
  template:
    metadata:
      labels:
        app: frontend-todo
    spec:
      containers:
        - name: frontend-todo
          image: ghcr.io/deztroid/test_app_f:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          env:
            - name: BACKEND_HOST
              value: /api/
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
              readOnly: true
          command: ["nginx", "-g", "daemon off;"]
      volumes:
        - name: nginx-config
          configMap:
            name: frontend-nginx-config