domain: todo-list.romanow-alex.ru
port: 3000

image:
  name: romanowalex/frontend-todo-list
  version: v2.0
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 128Mi