---
name: Publish
on:
  push:
    tags:
      - "v*.*"
jobs:
  publish:
    name: Publish to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build images
        timeout-minutes: 10
        run: docker compose build

      - name: Push images
        run: docker compose push

      - name: Create release
        uses: softprops/action-gh-release@v2
